---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "near-node.fullname" . }}-config
  namespace: {{ include "near-node.namespace" . }}
data:
  config.json: |
    {{- $defaultConfigYaml := include "near-node.config" . | nindent 4 }}
    {{- $defaultConfig := $defaultConfigYaml | fromYaml }}
    {{- $overrides := .Values.chain.configOverrides | toYaml | fromYaml }}
    {{- $mergedConfig := merge $defaultConfig $overrides | toJson }}
    {{- $mergedConfig | nindent 4 }}
