---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "near-node.fullname" . }}-config
  namespace: {{ include "near-node.namespace" . }}
data:
  config.json: |
    {{- define "near-node.config" -}}
    {{- if eq .Values.chain.network "testnet" }}
        {{- include "near-node.config.testnet" . | nindent 4 }}
    {{- else }}
        {{- include "near-node.config.mainnet" . | nindent 4 }}
    {{- end }}
    {{- end }}

    {{- $defaultConfigYaml := include "near-node.config" . }}
    {{- $defaultConfig := fromYaml $defaultConfigYaml }}
    {{- $overrides := .Values.chain.configOverrides }}
    {{- $mergedConfig := mergeOverwrite $defaultConfig $overrides }}
    {{- $mergedConfig | toJson | nindent 4 }}
