---
{{- if .Values.service.p2pTemplate.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "near-node.fullname" . }}-p2p
  namespace: {{ include "near-node.namespace" . }}
  labels:
    {{- include "near-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.p2pTemplate.type }}
  ports:
    - name: p2p
      port: {{ .Values.service.p2pTemplate.port }}
      {{ if .Values.service.p2pTemplate.nodePort }}
      nodePort: {{ .Values.service.p2pTemplate.nodePort }}
      {{ end }}
      targetPort: {{ .Values.service.p2pTemplate.port }}
  selector:
    {{- include "near-node.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.service.rpcTemplate.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "near-node.fullname" . }}-rpc
  namespace: {{ include "near-node.namespace" . }}
  labels:
    {{- include "near-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.rpcTemplate.type }}
  ports:
    - name: rpc
      port: {{ .Values.service.rpcTemplate.port }}
      {{ if .Values.service.rpcTemplate.nodePort }}
      nodePort: {{ .Values.service.rpcTemplate.nodePort }}
      {{ end }}
      targetPort: {{ .Values.service.rpcTemplate.port }}
    - name: metrics
      port: {{ .Values.service.metrics.port }}
      {{ if .Values.service.metrics.nodePort }}
      nodePort: {{ .Values.service.metrics.nodePort }}
      {{ end }}
      targetPort: {{ .Values.service.metrics.port }}
  selector:
    {{- include "near-node.selectorLabels" . | nindent 4 }}
{{- end }}
